name: Build & Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v5
    - name: Install deps
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build
        name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get build project
      uses: actions/download-artifact@v5
      with:
        name: build-files
